# Лабораторная работа №3

Леденцы

V1: освежить дыхание

V2: чувствовать себя увереннее

V3: освежить полость рта

V4: избавиться от неприятного вкуса

V5: заменитель сладкого

V6: хочется сладкого

V7: помогают сконцентрироваться

V8: отвлечься и подумать

V9: облегчить боль в горле

V10: избавиться от заложенности носа

V11: улучшить самочувствие

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import DBSCAN
from scipy.cluster.hierarchy import dendrogram, linkage, fcluster
import seaborn as sns

# Импорт данных

In [2]:
df = pd.read_csv('Леденцы.dat', sep=';')

print("Размер датасета:", df.shape)

print("\nПервые 5 строк данных:")
print(df.head())

print("\nОписательная статистика:")
print(df.describe())

Размер датасета: (338, 11)

Первые 5 строк данных:
   V1  V2  V3  V4  V5  V6  V7  V8  V9  V10  V11
0   4   5   5   5   3   3   3   3   3    3    3
1   5   4   5   5   3   3   3   3   3    3    3
2   5   5   4   5   3   3   3   3   3    3    3
3   5   4   5   5   3   3   3   3   3    3    3
4   4   5   5   5   3   3   3   3   3    3    3

Описательная статистика:
               V1          V2          V3          V4          V5          V6  \
count  338.000000  338.000000  338.000000  338.000000  338.000000  338.000000   
mean     3.544379    3.526627    3.517751    3.411243    3.207101    3.204142   
std      0.955748    0.956410    0.990150    0.992311    0.867314    0.869725   
min      2.000000    2.000000    2.000000    2.000000    2.000000    2.000000   
25%      3.000000    3.000000    3.000000    3.000000    3.000000    3.000000   
50%      3.000000    3.000000    3.000000    3.000000    3.000000    3.000000   
75%      5.000000    5.000000    5.000000    4.000000    3.000000   

Общая информация о данных

* Количество характеристик: 11 переменных (V1-V11)
* Шкала оценок: от 2 до 5 баллов
* Медиана по большинству переменных = 3, что указывает на преобладание нейтральных оценок

# Стандартизируем данные

Чтобы переменные с разной дисперсией вносили равный вклад в кластеризацию проведена кластеризация, иначе алгоритм учитывал бы в первую очередь переменные с большим разбросом значений (как например, V4 имеет std=0.99, V7 имеет std=0.84)

In [3]:
scaler = StandardScaler()
data_scaled = scaler.fit_transform(df)

# Кластеризация

In [6]:
# стандартные параметры
dbscan = DBSCAN(eps=0.5, metric='euclidean', min_samples=5)
# обучаем модель
dbscan.fit(data_scaled)
# смотрим на результаты кластеризации
dbscan.labels_


array([ 0,  1, -1,  1,  0,  1, -1,  1,  2, -1, -1, -1,  3, -1, -1,  3,  3,
        3,  3,  3,  3,  3, -1,  3,  3,  3,  3, -1, -1, -1,  2,  2,  0,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  4,  4,  4,  4,  4,  4,  4,  4, -1,
        4, -1,  2,  2,  2,  2,  2,  2,  2, -1, -1, -1,  2,  2, -1, -1,  2,
        2,  2,  2, -1,  2,  2,  2,  2, -1,  2,  2,  2, -1,  2,  2,  2,  2,
        1,  2,  2,  2,  2,  2,  2,  2,  2,  2,  0, -1, -1,  0,  0,  0, -1,
       -1,  0,  0,  0,  2,  2,  2,  2, -1,  5, -1,  5,  5,  5,  6,  6,  5,
        5,  6,  5,  7, -1,  6,  7,  7,  5,  5,  5,  5,  5,  6,  5,  5,  5,
        5,  5,  6, -1,  5,  6,  5,  7,  6,  5, -1,  5,  6,  7,  5,  5,  5,
        5,  6,  5,  5,  5,  5,  5,  5,  6,  5,  5,  5,  5, -1,  5,  7,  5,
       -1,  5, -1,  6,  5,  5,  7, -1, -1,  8,  8,  8, -1, -1, -1, -1,  5,
        5, -1,  8, -1, -1, -1,  8,  8, -1, -1,  5,  5,  5,  5,  5,  7,  5,
       -1, -1,  6,  6,  5,  7, -1, -1, -1, -1, -1,  7, -1,  6,  9, 10, 11,
       10, 11,  9,  9,  9

In [22]:
# Анализируем количество выбросов (-1)
outliers_count = counts[unique == -1][0] if -1 in unique else 0
print(f"Выбросов: {outliers_count} ({outliers_count/len(df)*100:.1f}%)")

Выбросов: 6 (1.8%)


In [23]:
# Вторая попытка (увеличиваем eps)
dbscan = DBSCAN(eps=2.0, metric='euclidean', min_samples=5)
dbscan.fit(data_scaled)
# смотрим на результаты кластеризации
dbscan.labels_

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  1,  1, -1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  2,  2,  2,
        2,  2,  2,  2,  2

In [21]:
unique, counts = np.unique(dbscan.labels_, return_counts=True)
results = np.asarray((unique, counts)).T
print("Результаты кластеризации:")
print(results)

Результаты кластеризации:
[[ -1   6]
 [  0 110]
 [  1 104]
 [  2  61]
 [  3  57]]


In [26]:
# Добавляем столбец cluster к таблице данных и выводим средние значения в каждом кластере
df['cluster'] = dbscan.labels_
df.groupby('cluster').mean()

V1        V2        V3        V4        V5        V6        V7  \
cluster                                                                         
-1       2.333333  3.333333  3.333333  3.333333  2.000000  2.333333  3.000000   
 0       4.845455  4.800000  4.836364  4.681818  3.036364  3.036364  3.000000   
 1       2.855769  2.788462  2.721154  2.567308  2.634615  2.605769  2.778846   
 2       3.000000  3.000000  3.000000  3.000000  4.852459  4.852459  3.000000   
 3       3.000000  3.000000  3.000000  2.947368  2.947368  2.947368  4.912281   

               V8        V9       V10       V11  
cluster                                          
-1       3.666667  4.333333  4.166667  4.166667  
 0       2.990909  3.072727  3.045455  3.045455  
 1       2.913462  4.951923  4.817308  4.865385  
 2       2.918033  2.754098  2.754098  2.754098  
 3       4.912281  3.000000  3.000000  3.000000

# Интерпретация результатов кластеризации

В результате кластерного анализа методом DBSCAN выделены четыре основных кластера потребителей леденцов и одна группа выбросов.

**Кластер -1 — выбросы.** Отсутствие четких паттернов поведения, возможно, ситуативные или неопределившиеся потребители.

**Кластер 0 — «Леденцы для свежести и уверенности» (V1-V4).**
Основная мотивация — освежение дыхания, ощущение уверенности, чистота полости рта, устранение неприятного вкуса.  
Средние оценки по этим признакам высоки.  
Вывод: Это «социально-ориентированные потребители», для которых леденцы являются инструментом поддержания комфорта в общении.

**Кластер 1 — «Леденцы для облегчения состояния» (V9-V11).**
Сюда входят респонденты, которые чаще всего употребляют леденцы для облегчения боли в горле, заложенности носа и улучшения самочувствия.  
Средние оценки по этим переменным значительно выше, чем по остальным.  
Вывод: Это «функциональные потребители», для которых леденцы выполняют скорее лечебную или поддерживающую функцию, чем развлекательную.

**Кластер 2 — «Леденцы как сладкое удовольствие» (V5-V6).**
Доминируют показатели «заменитель других кондитерских изделий» и «когда хочется чего-нибудь сладкого».  
Вывод: Эти потребители относятся к категории людей, для которых леденцы — просто приятное лакомство, источник сладости, без функциональной цели.

**Кластер 3 — «Леденцы для концентрации и отдыха» (V7-V8).**
Основные мотивации: помощь в концентрации, небольшой отдых и отвлечение.  
Вывод: Это «когнитивно-ориентированные потребители», которые используют леденцы как способ расслабления или повышения продуктивности.


# Сравнительный анализ методов кластеризации

В рамках выполнения лабораторных работ №1-3 проводилось исследование одного и того же датасета "Леденцы" с применением трех различных методов кластеризации: иерархического метода, метода k-средних и метода DBSCAN.

В результате анализа было установлено, что иерархический метод и метод k-средних демонстрируют согласованные результаты, формируя 4 четких кластера потребителей. Метод DBSCAN также выявил 4 основных кластера, но дополнительно идентифицировал пятую группу, помеченную как -1, которая представляет собой выбросы - наблюдения, не вошедшие в основные кластеры.

Сравнительный анализ показал, что наиболее наглядным и информативным для данного набора данных оказался **иерархический метод кластеризации**. Ключевое преимущество этого метода заключается в возможности визуализации структуры данных через дендрограмму, что позволяет наглядно проследить взаимосвязи между объектами и обосновать выбор количества кластеров на основе анализа "локтя" графика.

**Метод K-Means** продемонстрировал сравнимую с иерархическим методом эффективность в выделении кластеров, однако обладает меньшей визуальной наглядностью. Основное ограничение этого метода заключается в том, что расстояния между кластерами и процесс их формирования не являются очевидными из результатов работы алгоритма. Тем не менее, метод остается простым и удобным инструментом для практического применения.

**Метод DBSCAN** проявил себя как ценный инструмент для обнаружения аномалий и выбросов в данных, что является его неоспоримым преимуществом перед другими методами. Однако его практическое применение сопряжено с необходимостью тщательного подбора параметров, в частности радиуса окрестности (eps) и минимального количества объектов (min_samples). Этот процесс требует множественных итераций и экспериментальной проверки, что существенно увеличивает трудоемкость использования метода.